[package]
name = "taylorsrus/bin"
description = "Bin class for KISS cleanup."
version = "1.1.0"
license = "MIT"
authors = ["Joshua Taylor"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
